<?php

declare(strict_types=1);
namespace Drupal\brebo_calculation\Service;
use Drupal\Core\Database\Connection;
use InvalidArgumentException;
final class CalculationWorkAssignmentManager {
 public function __construct(private readonly Connection $database) {}
 public function save(int $calculationId,int $ownerUid,?int $dueDate,string $status,string $action,int $userId):array {if($calculationId<=0||$ownerUid<=0||trim($action)==='')throw new InvalidArgumentException('Calculatie, verantwoordelijke en actie zijn verplicht.');if(!in_array($status,['open','in_progress','waiting','ready','resolved','cancelled'],TRUE))throw new InvalidArgumentException('Ongeldige calculatiestatus.');$this->ensureStorage();$now=time();$existing=$this->database->select('brebo_calculation_work_assignment','a')->fields('a',['id'])->condition('calculation_id',$calculationId)->condition('status',['open','in_progress','waiting','ready'],'IN')->orderBy('changed','DESC')->range(0,1)->execute()->fetchField();$fields=['owner_uid'=>$ownerUid,'due_date'=>$dueDate,'status'=>$status,'action'=>trim($action),'changed'=>$now,'changed_by'=>$userId];if($existing){$id=(int)$existing;$this->database->update('brebo_calculation_work_assignment')->fields($fields)->condition('id',$id)->execute();}else{$id=(int)$this->database->insert('brebo_calculation_work_assignment')->fields(['calculation_id'=>$calculationId,'created'=>$now,'created_by'=>$userId]+$fields)->execute();}return $this->get($id);}
 public function forOwner(int $uid):array {$this->ensureStorage();$today=(new \DateTimeImmutable('today'))->getTimestamp();$tomorrow=(new \DateTimeImmutable('tomorrow'))->getTimestamp();$q=$this->database->select('brebo_calculation_work_assignment','a')->fields('a')->condition('owner_uid',$uid)->condition('status',['open','in_progress','waiting','ready'],'IN')->orderBy('due_date','ASC')->orderBy('changed','DESC');$items=array_map(static fn(object $r):array=>(array)$r,$q->execute()->fetchAll());foreach($items as &$i){$due=$i['due_date']===NULL?NULL:(int)$i['due_date'];$i['urgency']=$due===NULL?'no_deadline':($due<$today?'overdue':($due<$tomorrow?'today':'upcoming'));$i['days_overdue']=$due!==NULL&&$due<$today?(int)floor(($today-$due)/86400):0;}unset($i);return $items;}
 public function get(int $id):array {$this->ensureStorage();$r=$this->database->select('brebo_calculation_work_assignment','a')->fields('a')->condition('id',$id)->execute()->fetchAssoc();return $r===FALSE?[]:$r;}
 private function ensureStorage():void {$s=$this->database->schema();if($s->tableExists('brebo_calculation_work_assignment'))return;$s->createTable('brebo_calculation_work_assignment',['fields'=>['id'=>['type'=>'serial','not null'=>TRUE],'calculation_id'=>['type'=>'int','unsigned'=>TRUE,'not null'=>TRUE],'owner_uid'=>['type'=>'int','unsigned'=>TRUE,'not null'=>TRUE],'due_date'=>['type'=>'int','unsigned'=>TRUE,'not null'=>FALSE],'status'=>['type'=>'varchar','length'=>24,'not null'=>TRUE],'action'=>['type'=>'text','size'=>'big','not null'=>TRUE],'created'=>['type'=>'int','unsigned'=>TRUE,'not null'=>TRUE],'created_by'=>['type'=>'int','unsigned'=>TRUE,'not null'=>TRUE],'changed'=>['type'=>'int','unsigned'=>TRUE,'not null'=>TRUE],'changed_by'=>['type'=>'int','unsigned'=>TRUE,'not null'=>TRUE]],'primary key'=>['id'],'indexes'=>['calculation_status'=>['calculation_id','status'],'owner_status'=>['owner_uid','status'],'due_date'=>['due_date']]]);}
}
