<?php

declare(strict_types=1);

namespace Drupal\brebo_finance\Service;

use Drupal\Core\Database\Connection;
use InvalidArgumentException;
use RuntimeException;
use UnexpectedValueException;

/** Registers and verifies performed work against commitment lines. */
final class PerformanceReceiptManager {
  public function __construct(private readonly Connection $database,private readonly VatCalculator $decimal,private readonly FinancialEuroTraceFindingSynchronizer $euroTraceSynchronizer,private readonly PerformanceEvidenceReviewManager $evidenceReviews,private readonly PerformanceEvidenceRequirementResolver $evidenceRequirements,private readonly PerformanceLocationManager $locations) {}
  public function register(int $commitmentLineId,string $amountExVat,string $description,array $evidence,int $buildingNid,int $objectId,int $userId):int{
    if($userId<=0||$buildingNid<=0||$objectId<=0||trim($description)===''||$evidence===[])throw new InvalidArgumentException('Performance registration requires human user, building, object, description and evidence.');$line=$this->loadCommitmentLine($commitmentLineId);$profile=$this->evidenceRequirements->resolve(trim((string)($line['description']??$description)));$required=array_column($profile['requirements'],'code');$provided=[];foreach($evidence as $item){if(is_array($item)&&isset($item['type'],$item['ref'])&&trim((string)$item['ref'])!=='')$provided[(string)$item['type']]=(string)$item['ref'];}if($provided===[])throw new InvalidArgumentException('Evidence must be classified by required evidence type.');$missing=array_values(array_diff($required,array_keys($provided)));if($missing!==[])throw new RuntimeException('Required evidence is incomplete: '.implode(', ',$missing).'.');
    $amount=$this->positiveDecimal($amountExVat);$already=$this->registeredAmount($commitmentLineId);$remaining=$this->decimal->subtract((string)$line['amount_ex_vat'],$already);if($this->decimal->compare($amount,$remaining)>0)throw new RuntimeException('Registered performance exceeds the remaining commitment-line amount.');$now=time();$storedEvidence=[];foreach($profile['requirements'] as $req)$storedEvidence[]=['type'=>$req['code'],'label'=>$req['label'],'ref'=>$provided[$req['code']]];
    $transaction=$this->database->startTransaction();try{$id=(int)$this->database->insert('brebo_finance_performance_receipt')->fields(['project_nid'=>(int)$line['project_nid'],'commitment_line_id'=>$commitmentLineId,'status'=>'submitted','description'=>trim($description),'amount_ex_vat'=>$amount,'building_evidence_complete'=>0,'quality_accepted'=>0,'evidence'=>json_encode($storedEvidence,JSON_THROW_ON_ERROR|JSON_PRESERVE_ZERO_FRACTION),'verified'=>NULL,'verified_by'=>NULL,'verification_note'=>NULL,'created'=>$now,'created_by'=>$userId,'changed'=>$now,'changed_by'=>$userId])->execute();$this->locations->attach($id,(int)$line['project_nid'],$buildingNid,$objectId,$userId);$this->audit((int)$line['project_nid'],$id,'performance_submitted',['amount_ex_vat'=>$amount,'commitment_line_id'=>$commitmentLineId,'building_nid'=>$buildingNid,'object_id'=>$objectId,'evidence_activity'=>$profile['activity'],'evidence_types'=>$required],$userId);}catch(\Throwable $e){$transaction->rollBack();throw $e;}$this->euroTraceSynchronizer->sync('commitment',(int)$line['commitment_id'],$userId);return$id;
  }
  public function verify(int $receiptId,bool $buildingEvidenceComplete,bool $qualityAccepted,string $note,int $userId):void{
    if($userId<=0||trim($note)==='')throw new InvalidArgumentException('Verification requires a human verifier and note.');$receipt=$this->loadReceipt($receiptId);if($receipt['status']!=='submitted')throw new UnexpectedValueException('Only submitted performance can be verified.');if((int)$receipt['created_by']===$userId)throw new RuntimeException('The submitter may not verify their own performance receipt.');if($this->locations->forReceipt($receiptId)===null)throw new RuntimeException('Performance has no canonical building object location.');$accepted=$buildingEvidenceComplete&&$qualityAccepted;if($accepted){$summary=$this->evidenceReviews->summary($receiptId);if(!$summary['all_accepted'])throw new RuntimeException(sprintf('Performance cannot be verified: %d evidence item(s) pending and %d rejected.',$summary['pending'],$summary['rejected']));}$now=time();$this->database->update('brebo_finance_performance_receipt')->fields(['status'=>$accepted?'verified':'rejected','building_evidence_complete'=>$buildingEvidenceComplete?1:0,'quality_accepted'=>$qualityAccepted?1:0,'verified'=>$now,'verified_by'=>$userId,'verification_note'=>trim($note),'changed'=>$now,'changed_by'=>$userId])->condition('id',$receiptId)->execute();$line=$this->loadCommitmentLine((int)$receipt['commitment_line_id']);$this->audit((int)$line['project_nid'],$receiptId,$accepted?'performance_verified':'performance_rejected',['building_evidence_complete'=>$buildingEvidenceComplete,'quality_accepted'=>$qualityAccepted,'note'=>trim($note)],$userId);$this->euroTraceSynchronizer->sync('commitment',(int)$line['commitment_id'],$userId);
  }
  private function loadCommitmentLine(int $id):array{$q=$this->database->select('brebo_finance_commitment_line','l');$q->join('brebo_finance_commitment','c','c.id = l.commitment_id');$q->fields('l');$q->addField('c','project_nid');$q->addField('c','id','commitment_id');$row=$q->condition('l.id',$id)->execute()->fetchAssoc();if($row===false)throw new UnexpectedValueException('Commitment line does not exist.');return$row;}
  private function loadReceipt(int $id):array{$row=$this->database->select('brebo_finance_performance_receipt','r')->fields('r')->condition('id',$id)->execute()->fetchAssoc();if($row===false)throw new UnexpectedValueException('Performance receipt does not exist.');return$row;}
  private function registeredAmount(int $id):string{$q=$this->database->select('brebo_finance_performance_receipt','r');$q->condition('commitment_line_id',$id)->condition('status',['rejected'],'NOT IN');$q->addExpression('COALESCE(SUM(amount_ex_vat), 0)','registered_total');return(string)$q->execute()->fetchField();}
  private function positiveDecimal(string $v):string{$n=str_replace(',','.',trim($v));if($this->decimal->compare($n,'0')<=0)throw new InvalidArgumentException('Performance amount must be greater than zero.');return$n;}
  private function audit(int $p,int $r,string $a,array $payload,int $u):void{$this->database->insert('brebo_finance_audit')->fields(['project_nid'=>$p,'entity_type'=>'performance_receipt','entity_id'=>$r,'action'=>$a,'payload'=>json_encode($payload,JSON_THROW_ON_ERROR|JSON_PRESERVE_ZERO_FRACTION),'reason'=>'Performance evidence and quality verification for financial three-way matching.','created'=>time(),'created_by'=>$u])->execute();}
}
