<?php

declare(strict_types=1);
namespace Drupal\brebo_finance\Service;
use Drupal\brebo_calculation\Service\CalculationReadinessInspector;
use Drupal\brebo_calculation\Service\CalculationWorkAssignmentManager;
use Drupal\Core\Database\Connection;
final class PersonalWorkQueue {
 public function __construct(private readonly InvoiceBlockerActionManager $financeActions,private readonly CalculationWorkAssignmentManager $calculationActions,private readonly CalculationReadinessInspector $calculationReadiness,private readonly Connection $database){}
 public function build(int $uid):array {$finance=$this->financeActions->ownerSummary($uid);$calculations=$this->calculationActions->forOwner($uid);$items=[];foreach($finance['items'] as $i){$items[]=['domain'=>'finance','source'=>'invoice_blocker','id'=>(int)$i['id'],'project_nid'=>(int)$i['project_nid'],'title'=>(string)$i['action'],'status'=>(string)$i['status'],'due_date'=>$i['due_date']===NULL?NULL:(int)$i['due_date'],'urgency'=>(string)$i['urgency'],'days_overdue'=>(int)$i['days_overdue'],'href'=>'/brebo-office/finance/projects/'.(int)$i['project_nid'],'meta'=>['invoice_line_id'=>(int)$i['invoice_line_id']]];}foreach($calculations as $i){$id=(int)$i['calculation_id'];$items[]=['domain'=>'calculation','source'=>'calculation_assignment','id'=>(int)$i['id'],'project_nid'=>NULL,'title'=>(string)$i['action'],'status'=>(string)$i['status'],'due_date'=>$i['due_date']===NULL?NULL:(int)$i['due_date'],'urgency'=>(string)$i['urgency'],'days_overdue'=>(int)$i['days_overdue'],'href'=>'/admin/brebo/calculations/'.$id.'/workbench','meta'=>['calculation_id'=>$id]];$version=$this->latestCalculationVersion($id);if($version===NULL)continue;$r=$this->calculationReadiness->inspect($id,$version);$blocking=(int)($r['blocking']??0);$warnings=(int)($r['warnings']??0);if($blocking<=0&&$warnings<=0)continue;$items[]=['domain'=>'calculation','source'=>'calculation_readiness','id'=>'readiness-'.$id.'-'.$version,'project_nid'=>NULL,'title'=>$blocking>0?'Calculatie geblokkeerd: '.$blocking.' fout(en) oplossen vóór offertevrijgave':'Calculatie controleren: '.$warnings.' waarschuwing(en)','status'=>$blocking>0?'blocked':'review','due_date'=>$i['due_date']===NULL?NULL:(int)$i['due_date'],'urgency'=>$blocking>0&&$i['urgency']==='no_deadline'?'today':(string)$i['urgency'],'days_overdue'=>(int)$i['days_overdue'],'href'=>'/admin/brebo/calculations/'.$id.'/readiness','meta'=>['calculation_id'=>$id,'version'=>$version,'blocking'=>$blocking,'warnings'=>$warnings]];}usort($items,static function(array $a,array $b):int{$rank=['overdue'=>0,'today'=>1,'upcoming'=>2,'no_deadline'=>3];$x=($rank[$a['urgency']]??9)<=>($rank[$b['urgency']]??9);if($x!==0)return $x;return (($b['status']??'')==='blocked'?1:0)<=>(($a['status']??'')==='blocked'?1:0);});$s=['total'=>count($items),'overdue'=>0,'today'=>0,'upcoming'=>0,'no_deadline'=>0,'domains'=>[],'blocked'=>0];foreach($items as $i){$s[$i['urgency']]++;$s['domains'][$i['domain']]=($s['domains'][$i['domain']]??0)+1;if(($i['status']??'')==='blocked')$s['blocked']++;}return['summary'=>$s,'items'=>$items,'domains'=>['finance'=>['label'=>'Finance','count'=>$s['domains']['finance']??0],'calculation'=>['label'=>'Calculatie','count'=>$s['domains']['calculation']??0]]];}
 private function latestCalculationVersion(int $id):?string {if(!$this->database->schema()->tableExists('brebo_calculation_version'))return NULL;$v=$this->database->select('brebo_calculation_version','v')->fields('v',['version'])->condition('calculation_id',$id)->orderBy('version','DESC')->range(0,1)->execute()->fetchField();return $v===FALSE?NULL:(string)$v;}
}
